DROP DATABASE IF EXISTS test;
DROP USER IF EXISTS test;
CREATE USER test;
CREATE DATABASE test OWNER test;
GRANT ALL PRIVILEGES ON DATABASE test TO test;
COMMENT ON DATABASE test IS 'test db for dqp library';
